driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec
  format: doc

platforms:
  - name: centos-5.11
  - name: centos-6.7
  - name: centos-7.2
  - name: debian-7.10
    run_list: apt::default
  - name: debian-8.4
    run_list: apt::default
  - name: freebsd-9.3
    run_list: freebsd::portsnap
  - name: freebsd-10.2
    run_list: freebsd::portsnap
  - name: fedora-23
    run_list: yum::dnf_yum_compat
  - name: opensuse-13.2
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default
  - name: windows-2012r2-standard
    driver:
      box: chef/windows-server-2012r2-standard # private box in Chef's Atlas account
  - name: windows-2008r2-standard
    driver:
      box: chef/windows-server-2008r2-standard # private box in Chef's Atlas account
  - name: macosx-10.10
    driver:
      box: chef/macosx-10.10 # private box in Chef's Atlas account
      provider: vmware_fusion
  - name: macosx-10.11
    driver:
      box: chef/macosx-10.11 # private box in Chef's Atlas account
      provider: vmware_fusion

suites:
- name: default
  run_list:
  - recipe[git]
- name: source
  run_list:
  - recipe[git::source]
  excludes:
    - windows-2012r2-standard
    - windows-2008r2-standard
    - macosx-1010
    - macosx-1011
- name: server
  run_list:
  - recipe[git::server]
  excludes:
    - windows-2012r2-standard
    - windows-2008r2-standard
    - macosx-1010
    - macosx-1011
