driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec
  format: doc

platforms:
  - name: centos-5.11
  - name: centos-6.7
  - name: centos-7.2
  - name: debian-7.10
    run_list: apt::default
  - name: debian-8.4
    run_list: apt::default
  - name: freebsd-9.3
  - name: freebsd-10.2
  - name: fedora-23
    run_list: yum::dnf_yum_compat
  - name: opensuse-13.2
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default
  - name: windows-2008r2
    driver_config:
      box: chef/windows-server-2008r2-standard
  - name: windows-2012r2
    driver_config:
      box: chef/windows-server-2012r2-standard

suites:
- name: default
  run_list:
    - recipe[ohai_test::default]
