driver:
  name: dokken
  chef_version: latest
  privileged: true # because Docker and SystemD/Upstart

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  root_path: '/opt/verifier'
  sudo: false

platforms:
- name: debian-7
  driver:
    image: debian:7
    pid_one_command: /sbin/init

- name: debian-8
  driver:
    image: debian:8
    pid_one_command: /bin/systemd

- name: centos-7
  driver:
    image: centos:7
    platform: rhel
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN yum -y install lsof which

- name: ubuntu-12.04
  driver:
    image: ubuntu-upstart:12.04
    pid_one_command: /sbin/init

- name: ubuntu-14.04
  driver:
    image: ubuntu-upstart:14.04
    pid_one_command: /sbin/init

- name: ubuntu-16.04
  driver:
    image: ubuntu:16.04
    pid_one_command: /bin/systemd

suites:
  - name: default
    run_list:
      - recipe[apt]

  - name: cacher
    run_list:
      - recipe[apt_test::cacher]

  - name: compile-time
    run_list:
      - recipe[apt::default]
    attributes:
      apt:
        compile_time_update: true

  - name: lwrps
    run_list:
      - recipe[apt_test::lwrps]

  - name: unattended-upgrades
    run_list:
      - recipe[apt_test::unattended-upgrades]
    attributes:
      apt:
        unattended_upgrades:
          enable: true
